name: Deploy to ECS

on:
  push:
    branches:
      - main

env:
  ECR_REGISTRY: 209114680710.dkr.ecr.eu-central-1.amazonaws.com
  IMAGE_NAME: flatterstrom
  IMAGE_TAG: ${{ github.sha }}
  AWS_REGION: eu-central-1
  ECS_CLUSTER: power
  ECS_SERVICE: flatterservice

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to AWS CodeArtifact
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ env.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
      - name: Push Docker image
        run: |
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to Amazon ECS
        uses: docker://amazon/aws-cli:2.0.7


        with:
          args: ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment
